language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - gifsicle
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make checkstyle
  - make test
  - mpirun -N 1 python ./tests/test_parallelization.py
  - mpirun -N 2 python ./tests/test_parallelization.py
  - mpirun -N 4 python ./tests/test_parallelization.py
  - mpirun -N 6 python ./tests/test_parallelization.py
  - mpirun -N 8 python ./tests/test_parallelization.py
  - mpirun -N 9 python ./tests/test_parallelization.py
  - mpirun -N 14 python ./tests/test_parallelization.py
