language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenmpi-dev
      - openmpi-bin
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make checkstyle
  - make test
  - mpirun -N 2 ./tests/test_parallelization
